<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\InventoryMovement;
use App\Models\Product;
use App\Models\ProductSerial;
use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use App\Models\Supplier;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Migrates the Daikin Delivery Receipts / Purchase Orders (Jan–May 2026) from the
 * verified, corrected dataset in database/seeders/data/aircon_by_model.json.
 *
 * Source JSON is grouped by product model; each unit carries its serial_number,
 * document_no, document_date, po_no, so_no, storage_location.
 *
 * Behaviour (same as the live "create PO" flow — auto-received into inventory):
 *  - One PurchaseOrder per Document No (a delivery receipt).
 *  - delivery_number = Daikin Document No.  po_number is auto-generated by the model.
 *  - PO No / SO No / Storage Location kept in notes.
 *  - Each model line becomes a PurchaseOrderItem; every serial is stored in_stock,
 *    a stock_in InventoryMovement is logged, and the PO is marked received.
 *  - Missing product models are created (unit_type from prefix: R* = outdoor, else indoor).
 *  - Idempotent: a Document No already present is skipped; serials already in the DB
 *    for a product are skipped (logged), never duplicated.
 *  - Costs are 0 (not on the DRs).
 */
class PurchaseOrderJanuaryToMaySeeder extends Seeder
{
    public function run(): void
    {
        $file = database_path('seeders/data/aircon_by_model.json');
        if (!is_file($file)) {
            $this->command->error("Data file missing: {$file}");
            return;
        }
        $data = json_decode(file_get_contents($file), true);
        if (!is_array($data)) {
            $this->command->error('Could not parse data file.');
            return;
        }

        $supplier = Supplier::where('name', 'like', '%Daikin%')->first();
        $brand    = Brand::where('name', 'like', '%Daikin%')->first();
        $user     = User::orderBy('id')->first();
        if (!$supplier || !$brand || !$user) {
            $this->command->error('Missing Daikin supplier/brand or a user.');
            return;
        }

        // ── 1) Ensure every model exists as a product ──
        $newProducts = 0;
        foreach ($data as $mg) {
            $model = trim($mg['model']);
            $unitType = (strtoupper($model[0]) === 'R') ? 'outdoor' : 'indoor';
            $p = Product::firstOrCreate(
                ['model' => $model],
                [
                    'name'        => trim('Daikin ' . $model . ' ' . ($mg['description'] ?? '')),
                    'brand_id'    => $brand->id,
                    'unit_type'   => $unitType,
                    'description' => $mg['description'] ?? null,
                    'price'       => 0,
                    'cost'        => 0,
                    'is_active'   => true,
                ]
            );
            if ($p->wasRecentlyCreated) {
                $newProducts++;
                $this->command->info("Created product {$model} ({$unitType})");
            }
        }
        $products = Product::pluck('id', 'model');

        // ── 2) Group all units by Document No (one PO per DR) ──
        $drs = [];
        foreach ($data as $mg) {
            $model = trim($mg['model']);
            foreach ($mg['units'] as $u) {
                $doc = $u['document_no'];
                if (!isset($drs[$doc])) {
                    $drs[$doc] = [
                        'po'      => $u['po_no'] ?? null,
                        'so'      => $u['so_no'] ?? null,
                        'date'    => $u['document_date'] ?? null,
                        'storage' => $u['storage_location'] ?? null,
                        'items'   => [],
                    ];
                }
                $drs[$doc]['items'][$model][] = $u['serial_number'];
            }
        }

        // ── 3) Create auto-received POs ──
        $created = 0; $skippedDr = 0; $serialsMade = 0; $serialsSkipped = 0;

        foreach ($drs as $doc => $dr) {
            if (PurchaseOrder::where('delivery_number', $doc)->exists()) {
                $skippedDr++;
                continue;
            }

            DB::transaction(function () use ($doc, $dr, $supplier, $user, $products, &$created, &$serialsMade, &$serialsSkipped) {
                $date = $dr['date']
                    ? Carbon::createFromFormat('m/d/Y', $dr['date'])->toDateString()
                    : now()->toDateString();

                $notes = 'Migrated DR (Jan–May 2026). '
                    . 'PO No: ' . ($dr['po'] ?? '—')
                    . ' | SO No: ' . ($dr['so'] ?? '—')
                    . ' | Storage: ' . ($dr['storage'] ?? '—')
                    . ' [MIG-JANMAY:' . $doc . ']';

                $po = PurchaseOrder::create([
                    'supplier_id'            => $supplier->id,
                    'order_date'             => $date,
                    'expected_delivery_date' => $date,
                    'received_date'          => $date,
                    'subtotal'               => 0,
                    'tax'                    => 0,
                    'total'                  => 0,
                    'payment_type'           => 'full',
                    'amount_paid'            => 0,
                    'balance'                => 0,
                    'payment_status'         => 'paid',
                    'status'                 => 'received',
                    'delivery_number'        => $doc,
                    'notes'                  => $notes,
                    'user_id'                => $user->id,
                ]);
                $created++;

                foreach ($dr['items'] as $model => $serials) {
                    $pid = $products[$model] ?? null;
                    if (!$pid) { continue; }

                    $serials = collect($serials)->map(fn($s) => trim($s))->filter()->unique()->values();
                    $fresh = $serials->reject(fn($s) =>
                        ProductSerial::where('product_id', $pid)->where('serial_number', $s)->exists()
                    )->values();
                    $serialsSkipped += $serials->count() - $fresh->count();

                    $qty = $fresh->count();
                    if ($qty === 0) { continue; }

                    PurchaseOrderItem::create([
                        'purchase_order_id' => $po->id,
                        'product_id'        => $pid,
                        'quantity_ordered'  => $qty,
                        'quantity_received' => $qty,
                        'unit_cost'         => 0,
                        'discount_percent'  => 0,
                        'discount_amount'   => 0,
                        'discounted_cost'   => 0,
                        'total_cost'        => 0,
                    ]);

                    foreach ($fresh as $sn) {
                        ProductSerial::create([
                            'product_id'        => $pid,
                            'purchase_order_id' => $po->id,
                            'serial_number'     => $sn,
                            'status'            => 'in_stock',
                            'received_date'     => $date,
                        ]);
                        $serialsMade++;
                    }

                    $product = Product::find($pid);
                    $stockAfter = $product->inStockSerials()->count();
                    InventoryMovement::create([
                        'product_id'     => $pid,
                        'type'           => 'stock_in',
                        'quantity'       => $qty,
                        'stock_before'   => max(0, $stockAfter - $qty),
                        'stock_after'    => $stockAfter,
                        'reference_type' => 'PurchaseOrder',
                        'reference_id'   => $po->id,
                        'notes'          => 'Migrated from Daikin DR ' . $doc,
                        'user_id'        => $user->id,
                    ]);
                }
            });
        }

        $this->command->info("Products created: {$newProducts}");
        $this->command->info("POs created: {$created}, skipped (already migrated): {$skippedDr}");
        $this->command->info("Serials inserted: {$serialsMade}, skipped (duplicate already in DB): {$serialsSkipped}");
    }
}
